# Copyright 2016 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/google/marlin/proprietary/lib64/hw/power.marlin.so:system/lib64/hw/power.marlin.so \
    vendor/google/marlin/proprietary/lib64/hw/audio.primary.msm8996.so:system/lib64/hw/audio.primary.msm8996.so \
    vendor/google/marlin/proprietary/lib64/libprotobuf-cpp-full.so:system/lib64/libprotobuf-cpp-full.so \
    vendor/google/marlin/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/google/marlin/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/google/marlin/proprietary/lib/hw/power.marlin.so:system/lib/hw/power.marlin.so \
    vendor/google/marlin/proprietary/lib/hw/audio.primary.msm8996.so:system/lib/hw/audio.primary.msm8996.so \
    vendor/google/marlin/proprietary/lib/soundfx/libfmas.so:system/lib/soundfx/libfmas.so \
    vendor/google/marlin/proprietary/lib/libdmengine.so:system/lib/libdmengine.so \
    vendor/google/marlin/proprietary/lib/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
    vendor/google/marlin/proprietary/lib/libmotricity.so:system/lib/libmotricity.so \
    vendor/google/marlin/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
    vendor/google/marlin/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
    vendor/google/marlin/proprietary/etc/sysconfig/nexus.xml:system/etc/sysconfig/nexus.xml \
    vendor/google/marlin/proprietary/etc/sysconfig/google_vr_build.xml:system/etc/sysconfig/google_vr_build.xml \
    vendor/google/marlin/proprietary/etc/sysconfig/google.xml:system/etc/sysconfig/google.xml \
    vendor/google/marlin/proprietary/etc/sysconfig/marlin_common.xml:system/etc/sysconfig/marlin_common.xml \
    vendor/google/marlin/proprietary/etc/sysconfig/whitelist_com.android.omadm.service.xml:system/etc/sysconfig/whitelist_com.android.omadm.service.xml \
    vendor/google/marlin/proprietary/etc/sysconfig/google_build.xml:system/etc/sysconfig/google_build.xml \
    vendor/google/marlin/proprietary/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
    vendor/google/marlin/proprietary/etc/permissions/com.android.omadm.service.xml:system/etc/permissions/com.android.omadm.service.xml \
    vendor/google/marlin/proprietary/etc/permissions/com.verizon.apn.xml:system/etc/permissions/com.verizon.apn.xml \
    vendor/google/marlin/proprietary/etc/permissions/com.google.android.camera.experimental2016.xml:system/etc/permissions/com.google.android.camera.experimental2016.xml \
    vendor/google/marlin/proprietary/etc/permissions/obdm_permissions.xml:system/etc/permissions/obdm_permissions.xml \
    vendor/google/marlin/proprietary/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/google/marlin/proprietary/etc/permissions/com.verizon.provider.xml:system/etc/permissions/com.verizon.provider.xml \
    vendor/google/marlin/proprietary/etc/permissions/com.verizon.embms.xml:system/etc/permissions/com.verizon.embms.xml \
    vendor/google/marlin/qcom/adsprpcd:system/bin/adsprpcd:qcom \
    vendor/google/marlin/qcom/ATFWD-daemon:system/bin/ATFWD-daemon:qcom \
    vendor/google/marlin/qcom/athdiag:system/bin/athdiag:qcom \
    vendor/google/marlin/qcom/cnd:system/bin/cnd:qcom \
    vendor/google/marlin/qcom/cnss-daemon:system/bin/cnss-daemon:qcom \
    vendor/google/marlin/qcom/cnss_diag:system/bin/cnss_diag:qcom \
    vendor/google/marlin/qcom/diag_callback_sample:system/bin/diag_callback_sample:qcom \
    vendor/google/marlin/qcom/diag_dci_sample:system/bin/diag_dci_sample:qcom \
    vendor/google/marlin/qcom/diag_mdlog:system/bin/diag_mdlog:qcom \
    vendor/google/marlin/qcom/diag_socket_log:system/bin/diag_socket_log:qcom \
    vendor/google/marlin/qcom/diag_uart_log:system/bin/diag_uart_log:qcom \
    vendor/google/marlin/qcom/ftmdaemon:system/bin/ftmdaemon:qcom \
    vendor/google/marlin/qcom/gptest:system/bin/gptest:qcom \
    vendor/google/marlin/qcom/hal_proxy_daemon:system/bin/hal_proxy_daemon:qcom \
    vendor/google/marlin/qcom/hci_qcomm_init:system/bin/hci_qcomm_init:qcom \
    vendor/google/marlin/qcom/imscmservice:system/bin/imscmservice:qcom \
    vendor/google/marlin/qcom/imsdatadaemon:system/bin/imsdatadaemon:qcom \
    vendor/google/marlin/qcom/imsqmidaemon:system/bin/imsqmidaemon:qcom \
    vendor/google/marlin/qcom/ims_rtp_daemon:system/bin/ims_rtp_daemon:qcom \
    vendor/google/marlin/qcom/irsc_util:system/bin/irsc_util:qcom \
    vendor/google/marlin/qcom/loc_launcher:system/bin/loc_launcher:qcom \
    vendor/google/marlin/qcom/lowi-server:system/bin/lowi-server:qcom \
    vendor/google/marlin/qcom/mct-unit-test-app:system/bin/mct-unit-test-app:qcom \
    vendor/google/marlin/qcom/mdm_helper:system/bin/mdm_helper:qcom \
    vendor/google/marlin/qcom/mdm_helper_proxy:system/bin/mdm_helper_proxy:qcom \
    vendor/google/marlin/qcom/mm-qcamera-daemon:system/bin/mm-qcamera-daemon:qcom \
    vendor/google/marlin/qcom/myftm:system/bin/myftm:qcom \
    vendor/google/marlin/qcom/netmgrd:system/bin/netmgrd:qcom \
    vendor/google/marlin/qcom/nl_listener:system/bin/nl_listener:qcom \
    vendor/google/marlin/qcom/pktlogconf:system/bin/pktlogconf:qcom \
    vendor/google/marlin/qcom/PktRspTest:system/bin/PktRspTest:qcom \
    vendor/google/marlin/qcom/pm-proxy:system/bin/pm-proxy:qcom \
    vendor/google/marlin/qcom/pm-service:system/bin/pm-service:qcom \
    vendor/google/marlin/qcom/port-bridge:system/bin/port-bridge:qcom \
    vendor/google/marlin/qcom/qfipsverify:system/bin/qfipsverify:qcom \
    vendor/google/marlin/qcom/qmi_simple_ril_test:system/bin/qmi_simple_ril_test:qcom \
    vendor/google/marlin/qcom/qseecom_sample_client:system/bin/qseecom_sample_client:qcom \
    vendor/google/marlin/qcom/radish:system/bin/radish:qcom \
    vendor/google/marlin/qcom/rmt_storage:system/bin/rmt_storage:qcom \
    vendor/google/marlin/qcom/ssr_diag:system/bin/ssr_diag:qcom \
    vendor/google/marlin/qcom/ssr_setup:system/bin/ssr_setup:qcom \
    vendor/google/marlin/qcom/StoreKeybox:system/bin/StoreKeybox:qcom \
    vendor/google/marlin/qcom/subsystem_ramdump:system/bin/subsystem_ramdump:qcom \
    vendor/google/marlin/qcom/tbaseLoader:system/bin/tbaseLoader:qcom \
    vendor/google/marlin/qcom/test_bet_8996:system/bin/test_bet_8996:qcom \
    vendor/google/marlin/qcom/test_diag:system/bin/test_diag:qcom \
    vendor/google/marlin/qcom/test_module_pproc:system/bin/test_module_pproc:qcom \
    vendor/google/marlin/qcom/time_daemon:system/bin/time_daemon:qcom \
    vendor/google/marlin/qcom/wcnss_filter:system/bin/wcnss_filter:qcom \
    vendor/google/marlin/qcom/wdsdaemon:system/bin/wdsdaemon:qcom \
    vendor/google/marlin/qcom/WifiLogger_app:system/bin/WifiLogger_app:qcom \
    vendor/google/marlin/qcom/Bluetooth_cal.acdb:system/etc/acdbdata/Bluetooth_cal.acdb:qcom \
    vendor/google/marlin/qcom/General_cal.acdb:system/etc/acdbdata/General_cal.acdb:qcom \
    vendor/google/marlin/qcom/Global_cal.acdb:system/etc/acdbdata/Global_cal.acdb:qcom \
    vendor/google/marlin/qcom/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb:qcom \
    vendor/google/marlin/qcom/Hdmi_cal.acdb:system/etc/acdbdata/Hdmi_cal.acdb:qcom \
    vendor/google/marlin/qcom/Headset_cal.acdb:system/etc/acdbdata/Headset_cal.acdb:qcom \
    vendor/google/marlin/qcom/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb:qcom \
    vendor/google/marlin/qcom/imx179_chromatix.xml:system/etc/camera/imx179_chromatix.xml:qcom \
    vendor/google/marlin/qcom/imx378_chromatix.xml:system/etc/camera/imx378_chromatix.xml:qcom \
    vendor/google/marlin/qcom/msm8996_camera.xml:system/etc/camera/msm8996_camera.xml:qcom \
    vendor/google/marlin/qcom/ATT_profiles.xml:system/etc/cne/Nexus/ATT/ATT_profiles.xml:qcom \
    vendor/google/marlin/qcom/ROW_profiles.xml:system/etc/cne/Nexus/ROW/ROW_profiles.xml:qcom \
    vendor/google/marlin/qcom/VZW_profiles.xml:system/etc/cne/Nexus/VZW/VZW_profiles.xml:qcom \
    vendor/google/marlin/qcom/CHRE.cfg:system/etc/diag/CHRE.cfg:qcom \
    vendor/google/marlin/qcom/IMS.cfg:system/etc/diag/IMS.cfg:qcom \
    vendor/google/marlin/qcom/MarlinSailfish_Radio-generic.cfg:system/etc/diag/MarlinSailfish_Radio-generic.cfg:qcom \
    vendor/google/marlin/qcom/wlan.cfg:system/etc/diag/wlan.cfg:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_5_0.fw:system/etc/firmware/cpp_firmware_v1_5_0.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_5_2.fw:system/etc/firmware/cpp_firmware_v1_5_2.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw:qcom \
    vendor/google/marlin/qcom/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw:qcom \
    vendor/google/marlin/qcom/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin:qcom \
    vendor/google/marlin/qcom/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin:qcom \
    vendor/google/marlin/qcom/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin:qcom \
    vendor/google/marlin/qcom/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin:qcom \
    vendor/google/marlin/qcom/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin:qcom \
    vendor/google/marlin/qcom/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv:qcom \
    vendor/google/marlin/qcom/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv:qcom \
    vendor/google/marlin/qcom/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv:qcom \
    vendor/google/marlin/qcom/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv:qcom \
    vendor/google/marlin/qcom/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img:qcom \
    vendor/google/marlin/qcom/tfa98xx.cnt:system/etc/firmware/tfa98xx.cnt:qcom \
    vendor/google/marlin/qcom/flp.conf:system/etc/flp.conf:qcom \
    vendor/google/marlin/qcom/izat.conf:system/etc/izat.conf:qcom \
    vendor/google/marlin/qcom/lowi.conf:system/etc/lowi.conf:qcom \
    vendor/google/marlin/qcom/com.android.ims.rcsmanager.xml:system/etc/permissions/com.android.ims.rcsmanager.xml:qcom \
    vendor/google/marlin/qcom/embms.xml:system/etc/permissions/embms.xml:qcom \
    vendor/google/marlin/qcom/imscm.xml:system/etc/permissions/imscm.xml:qcom \
    vendor/google/marlin/qcom/qcrilhook.xml:system/etc/permissions/qcrilhook.xml:qcom \
    vendor/google/marlin/qcom/qti_permissions.xml:system/etc/permissions/qti_permissions.xml:qcom \
    vendor/google/marlin/qcom/qti-vzw-ims-internal.xml:system/etc/permissions/qti-vzw-ims-internal.xml:qcom \
    vendor/google/marlin/qcom/rcsservice.xml:system/etc/permissions/rcsservice.xml:qcom \
    vendor/google/marlin/qcom/telephonyservice.xml:system/etc/permissions/telephonyservice.xml:qcom \
    vendor/google/marlin/qcom/vzw_sso_permissions.xml:system/etc/permissions/vzw_sso_permissions.xml:qcom \
    vendor/google/marlin/qcom/qdcm_calib_data_M1_WQHD_SAMSUNG_S6E3HA3_5.5_command_mode_panel.xml:system/etc/qdcm_calib_data_M1_WQHD_SAMSUNG_S6E3HA3_5.5_command_mode_panel.xml:qcom \
    vendor/google/marlin/qcom/sap.conf:system/etc/sap.conf:qcom \
    vendor/google/marlin/qcom/com.android.ims.rcsmanager.jar:system/framework/com.android.ims.rcsmanager.jar:qcom \
    vendor/google/marlin/qcom/embmslibrary.jar:system/framework/embmslibrary.jar:qcom \
    vendor/google/marlin/qcom/qcrilhook.jar:system/framework/qcrilhook.jar:qcom \
    vendor/google/marlin/qcom/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar:qcom \
    vendor/google/marlin/qcom/rcsservice.jar:system/framework/rcsservice.jar:qcom \
    vendor/google/marlin/qcom/lib64/gps.default.so:system/lib64/hw/gps.default.so:qcom \
    vendor/google/marlin/qcom/lib64/libgps.utils.so:system/lib64/libgps.utils.so:qcom \
    vendor/google/marlin/qcom/lib64/libloc_api_v02.so:system/lib64/libloc_api_v02.so:qcom \
    vendor/google/marlin/qcom/lib64/libloc_core.so:system/lib64/libloc_core.so:qcom \
    vendor/google/marlin/qcom/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so:qcom \
    vendor/google/marlin/qcom/lib64/libloc_eng.so:system/lib64/libloc_eng.so:qcom \
    vendor/google/marlin/qcom/lib64/libminui.so:system/lib64/libminui.so:qcom \
    vendor/google/marlin/qcom/lib64/libtinyxml.so:system/lib64/libtinyxml.so:qcom \
    vendor/google/marlin/qcom/lib64/libwifi-hal-qcom.so:system/lib64/libwifi-hal-qcom.so:qcom \
    vendor/google/marlin/qcom/gps.default.so:system/lib/hw/gps.default.so:qcom \
    vendor/google/marlin/qcom/libgps.utils.so:system/lib/libgps.utils.so:qcom \
    vendor/google/marlin/qcom/libion.so:system/lib/libion.so:qcom \
    vendor/google/marlin/qcom/libloc_api_v02.so:system/lib/libloc_api_v02.so:qcom \
    vendor/google/marlin/qcom/libloc_core.so:system/lib/libloc_core.so:qcom \
    vendor/google/marlin/qcom/libloc_ds_api.so:system/lib/libloc_ds_api.so:qcom \
    vendor/google/marlin/qcom/libloc_eng.so:system/lib/libloc_eng.so:qcom \
    vendor/google/marlin/qcom/libminui.so:system/lib/libminui.so:qcom \
    vendor/google/marlin/qcom/libmm-qcamera.so:system/lib/libmm-qcamera.so:qcom \
    vendor/google/marlin/qcom/libtinyxml.so:system/lib/libtinyxml.so:qcom \
    vendor/google/marlin/qcom/bootimg.hmac:system/usr/qfipsverify/bootimg.hmac:qcom \
    vendor/google/marlin/qcom/qfipsverify.hmac:system/usr/qfipsverify/qfipsverify.hmac:qcom
